#!/usr/bin/python3
def m_funct(m):
    if m % 2 == 0:
        print("Weird")
    if m % 2 != 0 and m == range(2, 6):
        print("Not weird")
    if m % 2 != 0 and m == range(6, 21):
        print("Weird")
    if m % 2 != 0 and m > 20:
        print("Not weird")
m_funct(21)
