#!/usr/bin/python3

month_of = input("Enter Month: ")
month = month_of.lower()

if month == "january":
    print("The month of Janaury has 31 days.")
elif month == "february":
    print("The month of February has 28 or 29 days.")
elif month == "march":
    print("The month of March has 31 days.")
elif month == "april":
    print("The month of April has 30 days.")
elif month == "may":
    print("The month of May has 31 days.")
elif month == "june":
    print("The month of June has 30 days.")
elif month == "july":
    print("The month of July has 31 days.")
elif month == "august":
    print("The month of August has 31 days.")
elif month == "september":
    print("The month of September has 30 days.")
elif month == "october":
    print("The month of October has 31 days.")
elif month == "November":
    print("The month of November has 30 days.")
elif month == "December":
    print("The month of December has 31 days.")
